Fix MissingReferenceException
An interactive component that held by TouchAndHold can get destroyed
during delayMilis elappsed. Then TouchAndHold throw the following
error:

> MissingReferenceException: The object of type 'Button' has been
> destroyed but you are still trying to access it. Your script should
> either check if it is null or you should not destroy the object.

This patch introduce null-check after delayMilis elappsed.